FROM python:3.8-slim-buster
ENV AWS_ACCESS_ID = ''
ENV AWS_ACCESS_KEY = ''
ENV REGION_NAME = ''
ENV BUCKET_NAME = ''
ENV BUCKET_DIR = ''
ENV TEMP_DIR = '/app/.sys-cache'

RUN apt update
WORKDIR /app
COPY . .
RUN pip install requirements.txt
EXPOSE 80
CMD [ "uvicorn", "main:app","--host","0.0.0.0", "--port", "80"]